security:
  encoders:
    App\Entity\User: auto
  providers:
    user_provider:
      entity:
        class: App\Entity\User
        property: email
    customer_provider:
      entity:
        class: App\Entity\Customer
        property: phone
    tech_app_provider:
      memory:
        users:
          technician: { roles: [ 'ROLE_TECHNICIAN' ] }
    dealer_provider:
      memory:
        users:
          dealer: { roles: [ 'ROLE_ADMIN' ] }
    iservice_provider:
      memory:
        users:
          iservice: { roles: [ 'ROLE_ADMIN' ] }
    chain_provider:
      chain:
        providers: [ 'user_provider', 'customer_provider', 'tech_app_provider', 'dealer_provider', 'iservice_provider' ]
  role_hierarchy:
    ROLE_ADMIN: [ ROLE_SERVICE_MANAGER, ROLE_SERVICE_ADVISOR, ROLE_TECHNICIAN, ROLE_PARTS_ADVISOR, ROLE_SALES_MANAGER, ROLE_SALES_AGENT, ROLE_USER ]
    ROLE_SERVICE_MANAGER: [ ROLE_SERVICE_ADVISOR, ROLE_USER ]
    ROLE_SERVICE_ADVISOR: ROLE_USER
    ROLE_TECHNICIAN: ROLE_USER
    ROLE_PARTS_ADVISOR: ROLE_USER
    ROLE_SALES_MANAGER: [ ROLE_SALES_AGENT, ROLE_USER ]
    ROLE_SALES_AGENT: ROLE_USER
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api
      stateless: true
      anonymous: true
      provider: 'chain_provider'
      guard:
        authenticators:
          - App\Security\Authenticator
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/api/authentication/authenticate, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/security/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/security/validate, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/security/get-security-question, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/service-sms/twilio-incoming, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/service-sms/status-callback, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
    
