App\Soap\dealerbuilt\src\Models\EnvironmentPlacementType:
    properties:
        dealerNumber:
            expose: true
            access_type: public_method
            serialized_name: DealerNumber
            xml_element:
                namespace: 'http://schemas.datacontract.org/2004/07/DealerBuiltClient.Models'
            accessor:
                getter: getDealerNumber
                setter: setDealerNumber
            type: int
